version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: URUS
      ME_CONFIG_BASICAUTH_PASSWORD: URPASS
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: URROOT
      ME_CONFIG_MONGODB_ADMINPASSWORD: URPASSROOT
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: URROOT
      MONGO_INITDB_ROOT_PASSWORD: URPASSROOT
    ports:
      - 27017:27017
    volumes:
      - ./Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge

volumes:
    persistent:
